"""Optimum-ONNX supported architectures - generated reference.

Regenerate: uv run python tests/assets/generate_optimum_architectures.py
Source: optimum/exporters/onnx/model_configs.py
"""

from __future__ import annotations

from dataclasses import dataclass


@dataclass(frozen=True)
class ArchitectureInfo:
    """Describes a single optimum-onnx architecture registration."""

    tasks: tuple[str, ...]
    config_class: str
    category: str
    # text_encoder | text_decoder | seq2seq | vision | multimodal | audio | diffusers | other
    library: str  # transformers | diffusers | timm | sentence_transformers


OPTIMUM_ARCHITECTURES: dict[str, ArchitectureInfo] = {
    "bert": ArchitectureInfo(
        tasks=(
            "feature-extraction",
            "fill-mask",
            "multiple-choice",
            "question-answering",
            "text-classification",
            "token-classification",
        ),
        config_class="BertOnnxConfig",
        category="text_encoder",
        library="transformers",
    ),
    "visual_bert": ArchitectureInfo(
        tasks=("feature-extraction",),
        config_class="VisualBertOnnxConfig",
        category="multimodal",
        library="transformers",
    ),
    "albert": ArchitectureInfo(
        tasks=(
            "feature-extraction",
            "fill-mask",
            "multiple-choice",
            "question-answering",
            "text-classification",
            "token-classification",
        ),
        config_class="AlbertOnnxConfig",
        category="text_encoder",
        library="transformers",
    ),
    "convbert": ArchitectureInfo(
        tasks=(
            "feature-extraction",
            "fill-mask",
            "multiple-choice",
            "question-answering",
            "text-classification",
            "token-classification",
        ),
        config_class="ConvBertOnnxConfig",
        category="text_encoder",
        library="transformers",
    ),
    "electra": ArchitectureInfo(
        tasks=(
            "feature-extraction",
            "fill-mask",
            "multiple-choice",
            "question-answering",
            "text-classification",
            "token-classification",
        ),
        config_class="ElectraOnnxConfig",
        category="text_encoder",
        library="transformers",
    ),
    "roformer": ArchitectureInfo(
        tasks=(
            "feature-extraction",
            "fill-mask",
            "multiple-choice",
            "question-answering",
            "text-classification",
            "token-classification",
        ),
        config_class="RoFormerOnnxConfig",
        category="text_encoder",
        library="transformers",
    ),
    "squeezebert": ArchitectureInfo(
        tasks=(
            "feature-extraction",
            "fill-mask",
            "multiple-choice",
            "question-answering",
            "text-classification",
            "token-classification",
        ),
        config_class="SqueezeBertOnnxConfig",
        category="text_encoder",
        library="transformers",
    ),
    "mobilebert": ArchitectureInfo(
        tasks=(
            "feature-extraction",
            "fill-mask",
            "multiple-choice",
            "question-answering",
            "text-classification",
            "token-classification",
        ),
        config_class="MobileBertOnnxConfig",
        category="text_encoder",
        library="transformers",
    ),
    "nystromformer": ArchitectureInfo(
        tasks=(
            "feature-extraction",
            "fill-mask",
            "multiple-choice",
            "question-answering",
            "text-classification",
            "token-classification",
        ),
        config_class="NystromformerOnnxConfig",
        category="text_encoder",
        library="transformers",
    ),
    "xlm": ArchitectureInfo(
        tasks=(
            "feature-extraction",
            "fill-mask",
            "multiple-choice",
            "question-answering",
            "text-classification",
            "token-classification",
        ),
        config_class="XLMOnnxConfig",
        category="text_encoder",
        library="transformers",
    ),
    "splinter": ArchitectureInfo(
        tasks=("feature-extraction", "question-answering"),
        config_class="SplinterOnnxConfig",
        category="text_encoder",
        library="transformers",
    ),
    "rembert": ArchitectureInfo(
        tasks=(
            "feature-extraction",
            "fill-mask",
            "multiple-choice",
            "question-answering",
            "text-classification",
            "token-classification",
        ),
        config_class="RemBertOnnxConfig",
        category="text_encoder",
        library="transformers",
    ),
    "longformer": ArchitectureInfo(
        tasks=(
            "feature-extraction",
            "fill-mask",
            "multiple-choice",
            "question-answering",
            "text-classification",
            "token-classification",
        ),
        config_class="LongformerOnnxConfig",
        category="text_encoder",
        library="transformers",
    ),
    "megatron-bert": ArchitectureInfo(
        tasks=(
            "feature-extraction",
            "fill-mask",
            "multiple-choice",
            "question-answering",
            "text-classification",
            "token-classification",
        ),
        config_class="MegatronBertOnnxConfig",
        category="text_encoder",
        library="transformers",
    ),
    "distilbert": ArchitectureInfo(
        tasks=(
            "feature-extraction",
            "fill-mask",
            "multiple-choice",
            "question-answering",
            "text-classification",
            "token-classification",
        ),
        config_class="DistilBertOnnxConfig",
        category="text_encoder",
        library="transformers",
    ),
    "modernbert": ArchitectureInfo(
        tasks=("feature-extraction", "fill-mask", "text-classification", "token-classification"),
        config_class="ModernBertOnnxConfig",
        category="text_encoder",
        library="transformers",
    ),
    "mpnet": ArchitectureInfo(
        tasks=(
            "feature-extraction",
            "fill-mask",
            "multiple-choice",
            "question-answering",
            "text-classification",
            "token-classification",
        ),
        config_class="MPNetOnnxConfig",
        category="text_encoder",
        library="transformers",
    ),
    "roberta": ArchitectureInfo(
        tasks=(
            "feature-extraction",
            "fill-mask",
            "multiple-choice",
            "question-answering",
            "text-classification",
            "token-classification",
        ),
        config_class="RobertaOnnxConfig",
        category="text_encoder",
        library="transformers",
    ),
    "camembert": ArchitectureInfo(
        tasks=(
            "feature-extraction",
            "fill-mask",
            "multiple-choice",
            "question-answering",
            "text-classification",
            "token-classification",
        ),
        config_class="CamembertOnnxConfig",
        category="text_encoder",
        library="transformers",
    ),
    "flaubert": ArchitectureInfo(
        tasks=(
            "feature-extraction",
            "fill-mask",
            "multiple-choice",
            "question-answering",
            "text-classification",
            "token-classification",
        ),
        config_class="FlaubertOnnxConfig",
        category="text_encoder",
        library="transformers",
    ),
    "ibert": ArchitectureInfo(
        tasks=(
            "feature-extraction",
            "fill-mask",
            "multiple-choice",
            "question-answering",
            "text-classification",
            "token-classification",
        ),
        config_class="IBertOnnxConfig",
        category="text_encoder",
        library="transformers",
    ),
    "xlm-roberta": ArchitectureInfo(
        tasks=(
            "feature-extraction",
            "fill-mask",
            "multiple-choice",
            "question-answering",
            "text-classification",
            "token-classification",
        ),
        config_class="XLMRobertaOnnxConfig",
        category="text_encoder",
        library="transformers",
    ),
    "deberta": ArchitectureInfo(
        tasks=(
            "feature-extraction",
            "fill-mask",
            "question-answering",
            "text-classification",
            "token-classification",
        ),
        config_class="DebertaOnnxConfig",
        category="text_encoder",
        library="transformers",
    ),
    "markuplm": ArchitectureInfo(
        tasks=(
            "feature-extraction",
            "question-answering",
            "text-classification",
            "token-classification",
        ),
        config_class="MarkupLMOnnxConfig",
        category="text_encoder",
        library="transformers",
    ),
    "deberta-v2": ArchitectureInfo(
        tasks=(
            "feature-extraction",
            "fill-mask",
            "multiple-choice",
            "question-answering",
            "text-classification",
            "token-classification",
        ),
        config_class="DebertaV2OnnxConfig",
        category="text_encoder",
        library="transformers",
    ),
    "esm": ArchitectureInfo(
        tasks=("feature-extraction", "fill-mask", "text-classification", "token-classification"),
        config_class="EsmOnnxConfig",
        category="text_encoder",
        library="transformers",
    ),
    "gpt2": ArchitectureInfo(
        tasks=(
            "feature-extraction",
            "feature-extraction-with-past",
            "text-classification",
            "text-generation",
            "text-generation-with-past",
            "token-classification",
        ),
        config_class="GPT2OnnxConfig",
        category="text_decoder",
        library="transformers",
    ),
    "gptj": ArchitectureInfo(
        tasks=(
            "feature-extraction",
            "feature-extraction-with-past",
            "question-answering",
            "text-classification",
            "text-generation",
            "text-generation-with-past",
        ),
        config_class="GPTJOnnxConfig",
        category="text_decoder",
        library="transformers",
    ),
    "codegen": ArchitectureInfo(
        tasks=(
            "feature-extraction",
            "feature-extraction-with-past",
            "text-generation",
            "text-generation-with-past",
        ),
        config_class="CodeGenOnnxConfig",
        category="text_decoder",
        library="transformers",
    ),
    "imagegpt": ArchitectureInfo(
        tasks=("feature-extraction", "image-classification"),
        config_class="ImageGPTOnnxConfig",
        category="text_decoder",
        library="transformers",
    ),
    "decision_transformer": ArchitectureInfo(
        tasks=("feature-extraction", "reinforcement-learning"),
        config_class="DecisionTransformerOnnxConfig",
        category="other",
        library="transformers",
    ),
    "gpt_neo": ArchitectureInfo(
        tasks=(
            "feature-extraction",
            "feature-extraction-with-past",
            "text-classification",
            "text-generation",
            "text-generation-with-past",
        ),
        config_class="GPTNeoOnnxConfig",
        category="text_decoder",
        library="transformers",
    ),
    "gpt_neox": ArchitectureInfo(
        tasks=(
            "feature-extraction",
            "feature-extraction-with-past",
            "text-classification",
            "text-generation",
            "text-generation-with-past",
        ),
        config_class="GPTNeoXOnnxConfig",
        category="text_decoder",
        library="transformers",
    ),
    "opt": ArchitectureInfo(
        tasks=(
            "feature-extraction",
            "feature-extraction-with-past",
            "question-answering",
            "text-classification",
            "text-generation",
            "text-generation-with-past",
        ),
        config_class="OPTOnnxConfig",
        category="text_decoder",
        library="transformers",
    ),
    "llama": ArchitectureInfo(
        tasks=(
            "feature-extraction",
            "feature-extraction-with-past",
            "text-classification",
            "text-generation",
            "text-generation-with-past",
        ),
        config_class="LlamaOnnxConfig",
        category="text_decoder",
        library="transformers",
    ),
    "arcee": ArchitectureInfo(
        tasks=(
            "feature-extraction",
            "feature-extraction-with-past",
            "text-generation",
            "text-generation-with-past",
        ),
        config_class="ArceeOnnxConfig",
        category="text_decoder",
        library="transformers",
    ),
    "deepseek_v3": ArchitectureInfo(
        tasks=(
            "feature-extraction",
            "feature-extraction-with-past",
            "text-generation",
            "text-generation-with-past",
        ),
        config_class="DeepSeekV3OnnxConfig",
        category="text_decoder",
        library="transformers",
    ),
    "cohere": ArchitectureInfo(
        tasks=(
            "feature-extraction",
            "feature-extraction-with-past",
            "text-generation",
            "text-generation-with-past",
        ),
        config_class="CohereOnnxConfig",
        category="text_decoder",
        library="transformers",
    ),
    "glm": ArchitectureInfo(
        tasks=(
            "feature-extraction",
            "feature-extraction-with-past",
            "text-generation",
            "text-generation-with-past",
        ),
        config_class="GLMOnnxConfig",
        category="text_decoder",
        library="transformers",
    ),
    "helium": ArchitectureInfo(
        tasks=(
            "feature-extraction",
            "feature-extraction-with-past",
            "text-generation",
            "text-generation-with-past",
        ),
        config_class="HeliumOnnxConfig",
        category="text_decoder",
        library="transformers",
    ),
    "smollm3": ArchitectureInfo(
        tasks=(
            "feature-extraction",
            "feature-extraction-with-past",
            "text-classification",
            "text-generation",
            "text-generation-with-past",
        ),
        config_class="SmolLM3OnnxConfig",
        category="text_decoder",
        library="transformers",
    ),
    "stablelm": ArchitectureInfo(
        tasks=(
            "feature-extraction",
            "feature-extraction-with-past",
            "text-generation",
            "text-generation-with-past",
        ),
        config_class="StableLMOnnxConfig",
        category="text_decoder",
        library="transformers",
    ),
    "olmo": ArchitectureInfo(
        tasks=(
            "feature-extraction",
            "feature-extraction-with-past",
            "text-generation",
            "text-generation-with-past",
        ),
        config_class="OlmoOnnxConfig",
        category="text_decoder",
        library="transformers",
    ),
    "olmo2": ArchitectureInfo(
        tasks=(
            "feature-extraction",
            "feature-extraction-with-past",
            "text-generation",
            "text-generation-with-past",
        ),
        config_class="Olmo2OnnxConfig",
        category="text_decoder",
        library="transformers",
    ),
    "qwen2": ArchitectureInfo(
        tasks=(
            "feature-extraction",
            "feature-extraction-with-past",
            "text-classification",
            "text-generation",
            "text-generation-with-past",
            "token-classification",
        ),
        config_class="Qwen2OnnxConfig",
        category="text_decoder",
        library="transformers",
    ),
    "qwen3": ArchitectureInfo(
        tasks=(
            "feature-extraction",
            "feature-extraction-with-past",
            "text-classification",
            "text-generation",
            "text-generation-with-past",
        ),
        config_class="Qwen3OnnxConfig",
        category="text_decoder",
        library="transformers",
    ),
    "qwen3_moe": ArchitectureInfo(
        tasks=(
            "feature-extraction",
            "feature-extraction-with-past",
            "text-classification",
            "text-generation",
            "text-generation-with-past",
            "token-classification",
        ),
        config_class="Qwen3MoeOnnxConfig",
        category="text_decoder",
        library="transformers",
    ),
    "gemma": ArchitectureInfo(
        tasks=(
            "feature-extraction",
            "feature-extraction-with-past",
            "text-classification",
            "text-generation",
            "text-generation-with-past",
        ),
        config_class="GemmaOnnxConfig",
        category="text_decoder",
        library="transformers",
    ),
    "gemma2": ArchitectureInfo(
        tasks=(
            "feature-extraction",
            "feature-extraction-with-past",
            "text-classification",
            "text-generation",
            "text-generation-with-past",
        ),
        config_class="Gemma2OnnxConfig",
        category="text_decoder",
        library="transformers",
    ),
    "gemma3_text": ArchitectureInfo(
        tasks=(
            "feature-extraction",
            "feature-extraction-with-past",
            "text-generation",
            "text-generation-with-past",
        ),
        config_class="Gemma3TextOnnxConfig",
        category="text_decoder",
        library="transformers",
    ),
    "gemma3": ArchitectureInfo(
        tasks=(
            "feature-extraction",
            "feature-extraction-with-past",
            "text-classification",
            "text-generation",
            "text-generation-with-past",
        ),
        config_class="Gemma3OnnxConfig",
        category="text_decoder",
        library="transformers",
    ),
    "gpt_oss": ArchitectureInfo(
        tasks=(
            "feature-extraction",
            "feature-extraction-with-past",
            "text-generation",
            "text-generation-with-past",
        ),
        config_class="GPTOssOnnxConfig",
        category="text_decoder",
        library="transformers",
    ),
    "nemotron": ArchitectureInfo(
        tasks=(
            "feature-extraction",
            "feature-extraction-with-past",
            "text-generation",
            "text-generation-with-past",
        ),
        config_class="NemotronOnnxConfig",
        category="text_decoder",
        library="transformers",
    ),
    "granite": ArchitectureInfo(
        tasks=(
            "feature-extraction",
            "feature-extraction-with-past",
            "text-generation",
            "text-generation-with-past",
        ),
        config_class="GraniteOnnxConfig",
        category="text_decoder",
        library="transformers",
    ),
    "phi": ArchitectureInfo(
        tasks=(
            "feature-extraction",
            "feature-extraction-with-past",
            "text-classification",
            "text-generation",
            "text-generation-with-past",
        ),
        config_class="PhiOnnxConfig",
        category="text_decoder",
        library="transformers",
    ),
    "phi3": ArchitectureInfo(
        tasks=(
            "feature-extraction",
            "feature-extraction-with-past",
            "text-classification",
            "text-generation",
            "text-generation-with-past",
        ),
        config_class="Phi3OnnxConfig",
        category="text_decoder",
        library="transformers",
    ),
    "internlm2": ArchitectureInfo(
        tasks=("text-generation", "text-generation-with-past"),
        config_class="InternLM2OnnxConfig",
        category="text_decoder",
        library="transformers",
    ),
    "mistral": ArchitectureInfo(
        tasks=(
            "feature-extraction",
            "feature-extraction-with-past",
            "text-classification",
            "text-generation",
            "text-generation-with-past",
        ),
        config_class="MistralOnnxConfig",
        category="text_decoder",
        library="transformers",
    ),
    "mpt": ArchitectureInfo(
        tasks=(
            "feature-extraction",
            "feature-extraction-with-past",
            "text-classification",
            "text-generation",
            "text-generation-with-past",
            "token-classification",
        ),
        config_class="MPTOnnxConfig",
        category="text_decoder",
        library="transformers",
    ),
    "bloom": ArchitectureInfo(
        tasks=(
            "feature-extraction",
            "feature-extraction-with-past",
            "text-classification",
            "text-generation",
            "text-generation-with-past",
            "token-classification",
        ),
        config_class="BloomOnnxConfig",
        category="text_decoder",
        library="transformers",
    ),
    "gpt_bigcode": ArchitectureInfo(
        tasks=(
            "feature-extraction",
            "feature-extraction-with-past",
            "text-classification",
            "text-generation",
            "text-generation-with-past",
            "token-classification",
        ),
        config_class="GPTBigCodeOnnxConfig",
        category="text_decoder",
        library="transformers",
    ),
    "falcon": ArchitectureInfo(
        tasks=(
            "feature-extraction",
            "feature-extraction-with-past",
            "question-answering",
            "text-generation",
            "text-generation-with-past",
            "token-classification",
        ),
        config_class="FalconOnnxConfig",
        category="text_decoder",
        library="transformers",
    ),
    "t5": ArchitectureInfo(
        tasks=(
            "feature-extraction",
            "feature-extraction-with-past",
            "text2text-generation",
            "text2text-generation-with-past",
        ),
        config_class="T5OnnxConfig",
        category="seq2seq",
        library="transformers",
    ),
    "mt5": ArchitectureInfo(
        tasks=(
            "feature-extraction",
            "feature-extraction-with-past",
            "text2text-generation",
            "text2text-generation-with-past",
        ),
        config_class="MT5OnnxConfig",
        category="seq2seq",
        library="transformers",
    ),
    "longt5": ArchitectureInfo(
        tasks=(
            "feature-extraction",
            "feature-extraction-with-past",
            "text2text-generation",
            "text2text-generation-with-past",
        ),
        config_class="LongT5OnnxConfig",
        category="seq2seq",
        library="transformers",
    ),
    "m2m_100": ArchitectureInfo(
        tasks=(
            "feature-extraction",
            "feature-extraction-with-past",
            "text2text-generation",
            "text2text-generation-with-past",
        ),
        config_class="M2M100OnnxConfig",
        category="seq2seq",
        library="transformers",
    ),
    "bart": ArchitectureInfo(
        tasks=(
            "feature-extraction",
            "feature-extraction-with-past",
            "question-answering",
            "text-classification",
            "text-generation",
            "text-generation-with-past",
            "text2text-generation",
            "text2text-generation-with-past",
        ),
        config_class="BartOnnxConfig",
        category="seq2seq",
        library="transformers",
    ),
    "mbart": ArchitectureInfo(
        tasks=(
            "feature-extraction",
            "feature-extraction-with-past",
            "question-answering",
            "text-classification",
            "text-generation",
            "text-generation-with-past",
            "text2text-generation",
            "text2text-generation-with-past",
        ),
        config_class="MBartOnnxConfig",
        category="seq2seq",
        library="transformers",
    ),
    "blenderbot": ArchitectureInfo(
        tasks=(
            "feature-extraction",
            "feature-extraction-with-past",
            "text-generation",
            "text-generation-with-past",
            "text2text-generation",
            "text2text-generation-with-past",
        ),
        config_class="BlenderbotOnnxConfig",
        category="seq2seq",
        library="transformers",
    ),
    "blenderbot-small": ArchitectureInfo(
        tasks=(
            "feature-extraction",
            "feature-extraction-with-past",
            "text-generation",
            "text-generation-with-past",
            "text2text-generation",
            "text2text-generation-with-past",
        ),
        config_class="BlenderbotSmallOnnxConfig",
        category="seq2seq",
        library="transformers",
    ),
    "big_bird": ArchitectureInfo(
        tasks=(
            "feature-extraction",
            "fill-mask",
            "multiple-choice",
            "question-answering",
            "text-classification",
            "token-classification",
        ),
        config_class="BigBirdOnnxConfig",
        category="text_encoder",
        library="transformers",
    ),
    "bigbird_pegasus": ArchitectureInfo(
        tasks=(
            "feature-extraction",
            "feature-extraction-with-past",
            "question-answering",
            "text-classification",
            "text-generation",
            "text-generation-with-past",
            "text2text-generation",
            "text2text-generation-with-past",
        ),
        config_class="BigBirdPegasusOnnxConfig",
        category="seq2seq",
        library="transformers",
    ),
    "pegasus": ArchitectureInfo(
        tasks=(
            "feature-extraction",
            "feature-extraction-with-past",
            "text-generation",
            "text-generation-with-past",
            "text2text-generation",
            "text2text-generation-with-past",
        ),
        config_class="PegasusOnnxConfig",
        category="seq2seq",
        library="transformers",
    ),
    "marian": ArchitectureInfo(
        tasks=(
            "feature-extraction",
            "feature-extraction-with-past",
            "text-generation",
            "text-generation-with-past",
            "text2text-generation",
            "text2text-generation-with-past",
        ),
        config_class="MarianOnnxConfig",
        category="seq2seq",
        library="transformers",
    ),
    "vit": ArchitectureInfo(
        tasks=("feature-extraction", "image-classification", "masked-im"),
        config_class="ViTOnnxConfig",
        category="vision",
        library="transformers",
    ),
    "vitpose": ArchitectureInfo(
        tasks=("keypoint-detection",),
        config_class="VitPoseOnnxConfig",
        category="vision",
        library="transformers",
    ),
    "cvt": ArchitectureInfo(
        tasks=("feature-extraction", "image-classification"),
        config_class="CvTOnnxConfig",
        category="vision",
        library="transformers",
    ),
    "levit": ArchitectureInfo(
        tasks=("feature-extraction", "image-classification"),
        config_class="LevitOnnxConfig",
        category="vision",
        library="transformers",
    ),
    "deit": ArchitectureInfo(
        tasks=("feature-extraction", "image-classification", "masked-im"),
        config_class="DeiTOnnxConfig",
        category="vision",
        library="transformers",
    ),
    "beit": ArchitectureInfo(
        tasks=("feature-extraction", "image-classification"),
        config_class="BeitOnnxConfig",
        category="vision",
        library="transformers",
    ),
    "convnext": ArchitectureInfo(
        tasks=("feature-extraction", "image-classification"),
        config_class="ConvNextOnnxConfig",
        category="vision",
        library="transformers",
    ),
    "convnextv2": ArchitectureInfo(
        tasks=("feature-extraction", "image-classification"),
        config_class="ConvNextV2OnnxConfig",
        category="vision",
        library="transformers",
    ),
    "hiera": ArchitectureInfo(
        tasks=("feature-extraction", "image-classification"),
        config_class="HieraOnnxConfig",
        category="vision",
        library="transformers",
    ),
    "pvt": ArchitectureInfo(
        tasks=("feature-extraction", "image-classification"),
        config_class="PvtOnnxConfig",
        category="vision",
        library="transformers",
    ),
    "vit_mae": ArchitectureInfo(
        tasks=("feature-extraction",),
        config_class="VitMAEOnnxConfig",
        category="vision",
        library="transformers",
    ),
    "vit_msn": ArchitectureInfo(
        tasks=("feature-extraction", "image-classification"),
        config_class="VitMSNOnnxConfig",
        category="vision",
        library="transformers",
    ),
    "dinov2": ArchitectureInfo(
        tasks=("feature-extraction", "image-classification"),
        config_class="Dinov2OnnxConfig",
        category="vision",
        library="transformers",
    ),
    "mobilevit": ArchitectureInfo(
        tasks=("feature-extraction", "image-classification", "image-segmentation"),
        config_class="MobileViTOnnxConfig",
        category="vision",
        library="transformers",
    ),
    "regnet": ArchitectureInfo(
        tasks=("feature-extraction", "image-classification"),
        config_class="RegNetOnnxConfig",
        category="vision",
        library="transformers",
    ),
    "resnet": ArchitectureInfo(
        tasks=("feature-extraction", "image-classification"),
        config_class="ResNetOnnxConfig",
        category="vision",
        library="transformers",
    ),
    "detr": ArchitectureInfo(
        tasks=("feature-extraction", "image-segmentation", "object-detection"),
        config_class="DetrOnnxConfig",
        category="vision",
        library="transformers",
    ),
    "table-transformer": ArchitectureInfo(
        tasks=("feature-extraction", "object-detection"),
        config_class="TableTransformerOnnxConfig",
        category="vision",
        library="transformers",
    ),
    "yolos": ArchitectureInfo(
        tasks=("feature-extraction", "object-detection"),
        config_class="YolosOnnxConfig",
        category="vision",
        library="transformers",
    ),
    "swin": ArchitectureInfo(
        tasks=("feature-extraction", "image-classification", "masked-im"),
        config_class="SwinOnnxConfig",
        category="vision",
        library="transformers",
    ),
    "swinv2": ArchitectureInfo(
        tasks=("feature-extraction", "image-classification", "masked-im"),
        config_class="SwinV2OnnxConfig",
        category="vision",
        library="transformers",
    ),
    "swin2sr": ArchitectureInfo(
        tasks=("feature-extraction", "image-to-image"),
        config_class="Swin2srOnnxConfig",
        category="vision",
        library="transformers",
    ),
    "dpt": ArchitectureInfo(
        tasks=(
            "depth-estimation",
            "feature-extraction",
            "image-segmentation",
            "semantic-segmentation",
        ),
        config_class="DptOnnxConfig",
        category="vision",
        library="transformers",
    ),
    "glpn": ArchitectureInfo(
        tasks=("depth-estimation", "feature-extraction"),
        config_class="GlpnOnnxConfig",
        category="vision",
        library="transformers",
    ),
    "poolformer": ArchitectureInfo(
        tasks=("feature-extraction", "image-classification"),
        config_class="PoolFormerOnnxConfig",
        category="vision",
        library="transformers",
    ),
    "segformer": ArchitectureInfo(
        tasks=(
            "feature-extraction",
            "image-classification",
            "image-segmentation",
            "semantic-segmentation",
        ),
        config_class="SegformerOnnxConfig",
        category="vision",
        library="transformers",
    ),
    "mobilenet_v1": ArchitectureInfo(
        tasks=("feature-extraction", "image-classification"),
        config_class="MobileNetV1OnnxConfig",
        category="vision",
        library="transformers",
    ),
    "mobilenet_v2": ArchitectureInfo(
        tasks=("feature-extraction", "image-classification"),
        config_class="MobileNetV2OnnxConfig",
        category="vision",
        library="transformers",
    ),
    "maskformer": ArchitectureInfo(
        tasks=("feature-extraction", "image-segmentation"),
        config_class="MaskFormerOnnxConfig",
        category="vision",
        library="transformers",
    ),
    "donut-swin": ArchitectureInfo(
        tasks=("feature-extraction",),
        config_class="DonutSwinOnnxConfig",
        category="vision",
        library="transformers",
    ),
    "default-timm-config": ArchitectureInfo(
        tasks=("image-classification",),
        config_class="TimmDefaultOnnxConfig",
        category="vision",
        library="timm",
    ),
    "mgp-str": ArchitectureInfo(
        tasks=("feature-extraction",),
        config_class="MgpstrOnnxConfig",
        category="vision",
        library="transformers",
    ),
    "efficientnet": ArchitectureInfo(
        tasks=("feature-extraction", "image-classification"),
        config_class="EfficientNetOnnxConfig",
        category="vision",
        library="transformers",
    ),
    "transformer": ArchitectureInfo(
        tasks=("feature-extraction", "sentence-similarity"),
        config_class="SentenceTransformersTransformerOnnxConfig",
        category="text_encoder",
        library="sentence_transformers",
    ),
    "clip_vision_model": ArchitectureInfo(
        tasks=("feature-extraction",),
        config_class="CLIPVisionModelOnnxConfig",
        category="vision",
        library="transformers",
    ),
    "clip": ArchitectureInfo(
        tasks=("feature-extraction", "image-classification", "zero-shot-image-classification"),
        config_class="CLIPOnnxConfig",
        category="multimodal",
        library="transformers",
    ),
    "clip:sentence_transformers": ArchitectureInfo(
        tasks=("feature-extraction", "sentence-similarity"),
        config_class="SentenceTransformersCLIPOnnxConfig",
        category="multimodal",
        library="sentence_transformers",
    ),
    "clip-text-with-projection": ArchitectureInfo(
        tasks=("feature-extraction",),
        config_class="CLIPTextWithProjectionOnnxConfig",
        category="diffusers",
        library="diffusers",
    ),
    "clip-text": ArchitectureInfo(
        tasks=("feature-extraction",),
        config_class="CLIPTextOnnxConfig",
        category="diffusers",
        library="diffusers",
    ),
    "metaclip_2": ArchitectureInfo(
        tasks=("feature-extraction", "image-classification", "zero-shot-image-classification"),
        config_class="MetaCLIP2OnnxConfig",
        category="multimodal",
        library="transformers",
    ),
    "chinese_clip": ArchitectureInfo(
        tasks=("feature-extraction", "zero-shot-image-classification"),
        config_class="ChineseCLIPOnnxConfig",
        category="multimodal",
        library="transformers",
    ),
    "siglip": ArchitectureInfo(
        tasks=("feature-extraction", "zero-shot-image-classification"),
        config_class="SiglipOnnxConfig",
        category="multimodal",
        library="transformers",
    ),
    "siglip-text-with-projection": ArchitectureInfo(
        tasks=("feature-extraction",),
        config_class="SiglipTextWithProjectionOnnxConfig",
        category="text_encoder",
        library="transformers",
    ),
    "siglip-text": ArchitectureInfo(
        tasks=("feature-extraction",),
        config_class="SiglipTextOnnxConfig",
        category="text_encoder",
        library="transformers",
    ),
    "siglip_vision_model": ArchitectureInfo(
        tasks=("feature-extraction",),
        config_class="SiglipVisionModelOnnxConfig",
        category="vision",
        library="transformers",
    ),
    "unet-2d-condition": ArchitectureInfo(
        tasks=("semantic-segmentation",),
        config_class="UNetOnnxConfig",
        category="diffusers",
        library="diffusers",
    ),
    "vae-encoder": ArchitectureInfo(
        tasks=("semantic-segmentation",),
        config_class="VaeEncoderOnnxConfig",
        category="diffusers",
        library="diffusers",
    ),
    "vae-decoder": ArchitectureInfo(
        tasks=("semantic-segmentation",),
        config_class="VaeDecoderOnnxConfig",
        category="diffusers",
        library="diffusers",
    ),
    "t5-encoder": ArchitectureInfo(
        tasks=("feature-extraction",),
        config_class="T5EncoderOnnxConfig",
        category="diffusers",
        library="diffusers",
    ),
    "sd3-transformer-2d": ArchitectureInfo(
        tasks=("semantic-segmentation",),
        config_class="SD3TransformerOnnxConfig",
        category="diffusers",
        library="diffusers",
    ),
    "flux-transformer-2d": ArchitectureInfo(
        tasks=("semantic-segmentation",),
        config_class="FluxTransformerOnnxConfig",
        category="diffusers",
        library="diffusers",
    ),
    "groupvit": ArchitectureInfo(
        tasks=("feature-extraction",),
        config_class="GroupViTOnnxConfig",
        category="multimodal",
        library="transformers",
    ),
    "owlvit": ArchitectureInfo(
        tasks=("feature-extraction", "zero-shot-object-detection"),
        config_class="OwlViTOnnxConfig",
        category="multimodal",
        library="transformers",
    ),
    "owlv2": ArchitectureInfo(
        tasks=("feature-extraction", "zero-shot-object-detection"),
        config_class="OwlV2OnnxConfig",
        category="multimodal",
        library="transformers",
    ),
    "layoutlm": ArchitectureInfo(
        tasks=("feature-extraction", "fill-mask", "text-classification", "token-classification"),
        config_class="LayoutLMOnnxConfig",
        category="multimodal",
        library="transformers",
    ),
    "layoutlmv3": ArchitectureInfo(
        tasks=(
            "feature-extraction",
            "question-answering",
            "text-classification",
            "token-classification",
        ),
        config_class="LayoutLMv3OnnxConfig",
        category="multimodal",
        library="transformers",
    ),
    "lilt": ArchitectureInfo(
        tasks=(
            "feature-extraction",
            "question-answering",
            "text-classification",
            "token-classification",
        ),
        config_class="LiltOnnxConfig",
        category="multimodal",
        library="transformers",
    ),
    "data2vec-text": ArchitectureInfo(
        tasks=(
            "feature-extraction",
            "fill-mask",
            "multiple-choice",
            "question-answering",
            "text-classification",
            "token-classification",
        ),
        config_class="Data2VecTextOnnxConfig",
        category="text_encoder",
        library="transformers",
    ),
    "data2vec-vision": ArchitectureInfo(
        tasks=("feature-extraction", "image-classification"),
        config_class="Data2VecVisionOnnxConfig",
        category="vision",
        library="transformers",
    ),
    "perceiver": ArchitectureInfo(
        tasks=("fill-mask", "image-classification", "text-classification"),
        config_class="PerceiverOnnxConfig",
        category="multimodal",
        library="transformers",
    ),
    "hubert": ArchitectureInfo(
        tasks=("audio-classification", "automatic-speech-recognition", "feature-extraction"),
        config_class="HubertOnnxConfig",
        category="audio",
        library="transformers",
    ),
    "data2vec-audio": ArchitectureInfo(
        tasks=(
            "audio-classification",
            "audio-frame-classification",
            "audio-xvector",
            "automatic-speech-recognition",
            "feature-extraction",
        ),
        config_class="Data2VecAudioOnnxConfig",
        category="audio",
        library="transformers",
    ),
    "wav2vec2": ArchitectureInfo(
        tasks=(
            "audio-classification",
            "audio-frame-classification",
            "audio-xvector",
            "automatic-speech-recognition",
            "feature-extraction",
        ),
        config_class="Wav2Vec2OnnxConfig",
        category="audio",
        library="transformers",
    ),
    "wav2vec2-conformer": ArchitectureInfo(
        tasks=(
            "audio-classification",
            "audio-frame-classification",
            "audio-xvector",
            "automatic-speech-recognition",
            "feature-extraction",
        ),
        config_class="Wav2Vec2ConformerOnnxConfig",
        category="audio",
        library="transformers",
    ),
    "sew": ArchitectureInfo(
        tasks=("audio-classification", "automatic-speech-recognition", "feature-extraction"),
        config_class="SEWOnnxConfig",
        category="audio",
        library="transformers",
    ),
    "sew-d": ArchitectureInfo(
        tasks=("audio-classification", "automatic-speech-recognition", "feature-extraction"),
        config_class="SEWDOnnxConfig",
        category="audio",
        library="transformers",
    ),
    "unispeech": ArchitectureInfo(
        tasks=("audio-classification", "automatic-speech-recognition", "feature-extraction"),
        config_class="UniSpeechOnnxConfig",
        category="audio",
        library="transformers",
    ),
    "unispeech-sat": ArchitectureInfo(
        tasks=(
            "audio-classification",
            "audio-frame-classification",
            "audio-xvector",
            "automatic-speech-recognition",
            "feature-extraction",
        ),
        config_class="UniSpeechSATOnnxConfig",
        category="audio",
        library="transformers",
    ),
    "wavlm": ArchitectureInfo(
        tasks=(
            "audio-classification",
            "audio-frame-classification",
            "audio-xvector",
            "automatic-speech-recognition",
            "feature-extraction",
        ),
        config_class="WavLMOnnxConfig",
        category="audio",
        library="transformers",
    ),
    "mctct": ArchitectureInfo(
        tasks=("automatic-speech-recognition", "feature-extraction"),
        config_class="MCTCTOnnxConfig",
        category="audio",
        library="transformers",
    ),
    "audio-spectrogram-transformer": ArchitectureInfo(
        tasks=("audio-classification", "feature-extraction"),
        config_class="ASTOnnxConfig",
        category="other",
        library="transformers",
    ),
    "moonshine": ArchitectureInfo(
        tasks=(
            "automatic-speech-recognition",
            "automatic-speech-recognition-with-past",
            "feature-extraction",
            "feature-extraction-with-past",
        ),
        config_class="MoonshineOnnxConfig",
        category="audio",
        library="transformers",
    ),
    "whisper": ArchitectureInfo(
        tasks=(
            "audio-classification",
            "automatic-speech-recognition",
            "automatic-speech-recognition-with-past",
            "feature-extraction",
            "feature-extraction-with-past",
        ),
        config_class="WhisperOnnxConfig",
        category="audio",
        library="transformers",
    ),
    "musicgen": ArchitectureInfo(
        tasks=("text-to-audio",),
        config_class="MusicgenOnnxConfig",
        category="seq2seq",
        library="transformers",
    ),
    "speecht5": ArchitectureInfo(
        tasks=("text-to-audio",),
        config_class="SpeechT5OnnxConfig",
        category="seq2seq",
        library="transformers",
    ),
    "vits": ArchitectureInfo(
        tasks=("text-to-audio",),
        config_class="VitsOnnxConfig",
        category="text_encoder",
        library="transformers",
    ),
    "speech_to_text": ArchitectureInfo(
        tasks=(
            "automatic-speech-recognition",
            "automatic-speech-recognition-with-past",
            "feature-extraction",
            "feature-extraction-with-past",
        ),
        config_class="Speech2TextOnnxConfig",
        category="audio",
        library="transformers",
    ),
    "trocr": ArchitectureInfo(
        tasks=("feature-extraction", "feature-extraction-with-past"),
        config_class="TrOCROnnxConfig",
        category="seq2seq",
        library="transformers",
    ),
    "vision-encoder-decoder": ArchitectureInfo(
        tasks=("image-to-text", "image-to-text-with-past"),
        config_class="VisionEncoderDecoderOnnxConfig",
        category="seq2seq",
        library="transformers",
    ),
    "sam": ArchitectureInfo(
        tasks=("feature-extraction",),
        config_class="SamOnnxConfig",
        category="other",
        library="transformers",
    ),
    "pix2struct": ArchitectureInfo(
        tasks=("image-to-text", "image-to-text-with-past"),
        config_class="Pix2StructOnnxConfig",
        category="seq2seq",
        library="transformers",
    ),
    "encoder-decoder": ArchitectureInfo(
        tasks=("text2text-generation", "text2text-generation-with-past"),
        config_class="EncoderDecoderOnnxConfig",
        category="seq2seq",
        library="transformers",
    ),
    "patchtst": ArchitectureInfo(
        tasks=("feature-extraction", "time-series-forecasting"),
        config_class="PatchTSTOnnxConfig",
        category="other",
        library="transformers",
    ),
    "patchtsmixer": ArchitectureInfo(
        tasks=("feature-extraction", "time-series-forecasting"),
        config_class="PatchTSMixerOnnxConfig",
        category="other",
        library="transformers",
    ),
    "rt_detr": ArchitectureInfo(
        tasks=("object-detection",),
        config_class="RTDetrOnnxConfig",
        category="vision",
        library="transformers",
    ),
    "rt_detr_v2": ArchitectureInfo(
        tasks=("object-detection",),
        config_class="RTDetrV2OnnxConfig",
        category="vision",
        library="transformers",
    ),
    "colpali": ArchitectureInfo(
        tasks=("feature-extraction",),
        config_class="ColPaliOnnxConfig",
        category="text_decoder",
        library="transformers",
    ),
    "d_fine": ArchitectureInfo(
        tasks=("object-detection",),
        config_class="DFineOnnxConfig",
        category="vision",
        library="transformers",
    ),
    "gemma2-text-encoder": ArchitectureInfo(
        tasks=("feature-extraction",),
        config_class="Gemma2TextEncoderOnnxConfig",
        category="diffusers",
        library="diffusers",
    ),
    "sana-transformer": ArchitectureInfo(
        tasks=("semantic-segmentation",),
        config_class="SanaTransformerOnnxConfig",
        category="diffusers",
        library="diffusers",
    ),
    "dcae-encoder": ArchitectureInfo(
        tasks=("semantic-segmentation",),
        config_class="DcaeEncoderOnnxConfig",
        category="diffusers",
        library="diffusers",
    ),
    "dcae-decoder": ArchitectureInfo(
        tasks=("semantic-segmentation",),
        config_class="DcaeDecoderOnnxConfig",
        category="diffusers",
        library="diffusers",
    ),
}
