# -------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License.
# --------------------------------------------------------------------------
"""RewritePipe integration tests using the pattern infrastructure.

Verifies that RewritePipe correctly integrates with modelkit.pattern
(PatternMatcher, PatternRewriter, REWRITE_GROUPS) and produces ONNX models
that are structurally valid and correctly rewritten.

Cardinal Rules followed:
- CARDINAL RULE #1: No hardcoded model architectures or node names.
- CARDINAL RULE #2: All test results generated by code at runtime.
- CARDINAL RULE #3: Tests must run and pass (pytest).
- CARDINAL RULE #4: Never skip tests because they fail.

All ONNX models are built programmatically from PatternInputGenerator
instances so no model files are required on disk.
"""

from __future__ import annotations

import onnx
import pytest

from winml.modelkit.onnx import ONNXDomain
from winml.modelkit.optim.pipes.rewrite import RewritePipe
from winml.modelkit.optim.pipes.rewrite_rules import REWRITE_GROUPS
from winml.modelkit.pattern.base import PatternMatcher

# Reuse the conftest helpers (available as module-level functions)
from .conftest import generate_self_matching_model


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

TEST_DOMAIN_VERSIONS: dict[ONNXDomain, int] = {ONNXDomain.AI_ONNX: 17}


def _count_pattern_matches(model: onnx.ModelProto, pattern_name: str) -> int:
    """Return number of times a named pattern matches in the model."""
    from winml.modelkit.pattern.base import get_pattern_input_generator

    gen_class = get_pattern_input_generator(pattern_name)
    gen = gen_class(domain_versions=TEST_DOMAIN_VERSIONS)
    matcher = PatternMatcher(model)
    matcher.register_pattern(gen.pattern)
    return len(matcher.match())


def _gelu_cap_name() -> str | None:
    """Return the capability name for any GELU rewrite group, or None."""
    group = next((g for g in REWRITE_GROUPS if "gelu" in g.pattern_id.lower()), None)
    return group.flag_name if group is not None else None


def _gelu_cap_name_for_variant(gelu_variant: str) -> str | None:
    """Return the capability name for the group containing gelu_variant, or None."""
    source_name = f"{gelu_variant}Pattern"
    group = next((g for g in REWRITE_GROUPS if source_name in g.sources), None)
    return group.flag_name if group is not None else None


def _gemm_cap_name() -> str | None:
    """Return the capability name for the MatMulAdd/Gemm rewrite group, or None."""
    group = next((g for g in REWRITE_GROUPS if "gemm" in g.pattern_id.lower()), None)
    return group.flag_name if group is not None else None


# ---------------------------------------------------------------------------
# Round-trip tests: match patterns, rewrite, verify result
# ---------------------------------------------------------------------------


class TestRewritePipeRoundTrip:
    """Round-trip: match source patterns, rewrite, verify no source patterns remain."""

    @pytest.mark.parametrize("gelu_variant", ["Gelu1", "Gelu2", "Gelu3"])
    def test_gelu_rewrite_removes_source_pattern(self, gelu_variant: str) -> None:
        """After rewriting there should be no remaining source pattern matches."""
        cap_name = _gelu_cap_name_for_variant(gelu_variant)
        if cap_name is None:
            pytest.skip(f"No rewrite group found for {gelu_variant}")

        model, _, _ = generate_self_matching_model(gelu_variant)

        before = _count_pattern_matches(model, gelu_variant)
        assert before >= 1, f"Expected ≥1 {gelu_variant} match before rewriting, got {before}"

        config = RewritePipe.build_config(**{cap_name.replace("-", "_"): True})
        result = RewritePipe().process(model, config)

        after = _count_pattern_matches(result, gelu_variant)
        assert after == 0, f"Expected 0 {gelu_variant} matches after rewriting, got {after}"

    def test_matmul_add_rewrite_removes_source_pattern(self) -> None:
        """After rewriting there should be no remaining MatMulAdd matches."""
        cap_name = _gemm_cap_name()
        if cap_name is None:
            pytest.skip("No Gemm/MatMulAdd rewrite group found")

        model, _, _ = generate_self_matching_model("MatMulAdd")

        before = _count_pattern_matches(model, "MatMulAdd")
        assert before >= 1, f"Expected ≥1 MatMulAdd match before rewriting, got {before}"

        config = RewritePipe.build_config(**{cap_name.replace("-", "_"): True})
        result = RewritePipe().process(model, config)

        after = _count_pattern_matches(result, "MatMulAdd")
        assert after == 0, f"Expected 0 MatMulAdd matches after rewriting, got {after}"

    @pytest.mark.parametrize("gelu_variant", ["Gelu1", "Gelu2", "Gelu3"])
    def test_gelu_rewrite_produces_valid_onnx(self, gelu_variant: str) -> None:
        """Rewritten model must pass onnx.checker.check_model."""
        cap_name = _gelu_cap_name_for_variant(gelu_variant)
        if cap_name is None:
            pytest.skip(f"No rewrite group found for {gelu_variant}")

        model, _, _ = generate_self_matching_model(gelu_variant)
        config = RewritePipe.build_config(**{cap_name.replace("-", "_"): True})
        result = RewritePipe().process(model, config)
        onnx.checker.check_model(result)

    def test_matmul_add_rewrite_produces_valid_onnx(self) -> None:
        """Rewritten MatMulAdd model must pass onnx.checker.check_model."""
        cap_name = _gemm_cap_name()
        if cap_name is None:
            pytest.skip("No Gemm/MatMulAdd rewrite group found")

        model, _, _ = generate_self_matching_model("MatMulAdd")
        config = RewritePipe.build_config(**{cap_name.replace("-", "_"): True})
        result = RewritePipe().process(model, config)
        onnx.checker.check_model(result)


# ---------------------------------------------------------------------------
# Edge cases: model with no matching patterns
# ---------------------------------------------------------------------------


class TestRewritePipeNoMatchEdgeCases:
    """Correct behaviour when the model has no matching patterns."""

    def test_no_op_when_model_has_no_gelu(self) -> None:
        """When the model has no GELU patterns node count must not change."""
        cap_name = _gelu_cap_name()
        if cap_name is None:
            pytest.skip("No GELU rewrite group found")

        # MatMulAdd model has no GELU patterns
        model, _, _ = generate_self_matching_model("MatMulAdd")
        original_node_count = len(model.graph.node)

        config = RewritePipe.build_config(**{cap_name.replace("-", "_"): True})
        result = RewritePipe().process(model, config)

        assert len(result.graph.node) == original_node_count

    def test_no_op_when_model_has_no_matmul_add(self) -> None:
        """When the model has no MatMulAdd patterns node count must not change."""
        cap_name = _gemm_cap_name()
        if cap_name is None:
            pytest.skip("No Gemm rewrite group found")

        model, _, _ = generate_self_matching_model("Gelu1")
        original_node_count = len(model.graph.node)

        config = RewritePipe.build_config(**{cap_name.replace("-", "_"): True})
        result = RewritePipe().process(model, config)

        assert len(result.graph.node) == original_node_count

    def test_all_disabled_returns_same_object(self) -> None:
        """With no rules process() must return the same object."""
        model, _, _ = generate_self_matching_model("Gelu1")
        config = RewritePipe.build_config()
        result = RewritePipe().process(model, config)
        assert result is model
