# -------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License.
# --------------------------------------------------------------------------
"""RewritePipe tests for the batchedconstmatmul-untied rewrite.

Exercises the source/target patterns in
``winml.modelkit.pattern.batched_const_matmul_patterns`` end-to-end through
``RewritePipe``: a batched (rank >= 3) MatMul with one constant operand is
rewritten so the constant flows through ``Add(const, runtime-zero)``, leaving
numerics unchanged while making the operand runtime-valued.

Cardinal Rules followed:
- #1: No hardcoded model architectures or node names.
- #2: All expected results generated by code at runtime (ORT reference run).
- #3: Tests run and pass under pytest.
"""

from __future__ import annotations

import numpy as np
import onnx
import onnxruntime as ort

from winml.modelkit.optim.pipes.rewrite import RewritePipe


_CAP_KWARG = "batchedconstmatmul_untied"


def _build_model(
    *,
    const_on_rhs: bool,
    const_rank: int = 3,
    dynamic_batch: bool = True,
    both_constant: bool = False,
) -> onnx.ModelProto:
    """Build a single-MatMul model with one rank-``const_rank`` constant operand.

    The dynamic operand carries a symbolic batch dim when ``dynamic_batch`` is
    True, which is the case the base pattern matcher would normally reject.
    """
    rng = np.random.RandomState(0)
    batch: int | str = "batch" if dynamic_batch else 2

    if const_on_rhs:
        # dyn [batch,3,4] @ const W -> [batch,3,5]
        dyn_shape = [batch, 3, 4]
        w_arr = rng.randn(1, 4, 5).astype(np.float32)
        if const_rank == 2:
            w_arr = w_arr[0]  # [4,5]
        out_shape = [batch, 3, 5]
        mm_inputs = ["dyn", "W"]
    else:
        # const W @ dyn [batch,4,5] -> [batch,3,5]
        dyn_shape = [batch, 4, 5]
        w_arr = rng.randn(1, 3, 4).astype(np.float32)
        if const_rank == 2:
            w_arr = w_arr[0]  # [3,4]
        out_shape = [batch, 3, 5]
        mm_inputs = ["W", "dyn"]

    initializers = [onnx.numpy_helper.from_array(w_arr, "W")]
    graph_inputs = [
        onnx.helper.make_tensor_value_info("dyn", onnx.TensorProto.FLOAT, dyn_shape)
    ]

    if both_constant:
        # Replace the dynamic operand with a second constant of matching shape.
        dyn_concrete = [d if isinstance(d, int) else 2 for d in dyn_shape]
        initializers.append(
            onnx.numpy_helper.from_array(rng.randn(*dyn_concrete).astype(np.float32), "dyn")
        )
        graph_inputs = []

    matmul = onnx.helper.make_node("MatMul", mm_inputs, ["out"], name="batched_matmul")
    graph = onnx.helper.make_graph(
        [matmul],
        "batched_const_matmul",
        graph_inputs,
        [onnx.helper.make_tensor_value_info("out", onnx.TensorProto.FLOAT, out_shape)],
        initializer=initializers,
    )
    return onnx.helper.make_model(graph, opset_imports=[onnx.helper.make_opsetid("", 17)])


def _run(model: onnx.ModelProto, feed: dict[str, np.ndarray]) -> np.ndarray:
    sess = ort.InferenceSession(model.SerializeToString(), providers=["CPUExecutionProvider"])
    return sess.run(None, feed)[0]


def _rewrite(model: onnx.ModelProto) -> onnx.ModelProto:
    pipe = RewritePipe()
    return pipe.process(model, pipe.build_config(**{_CAP_KWARG: True}))


class TestBatchedConstMatMulUntieRewrite:
    """End-to-end rewrite behavior via RewritePipe."""

    def test_constant_operand_becomes_runtime_valued(self) -> None:
        """The MatMul no longer consumes the initializer directly; an Add feeds it."""
        model = _build_model(const_on_rhs=True)
        result = _rewrite(model)

        matmul = next(n for n in result.graph.node if n.op_type == "MatMul")
        initializer_names = {init.name for init in result.graph.initializer}
        assert not (set(matmul.input) & initializer_names)
        add_nodes = [n for n in result.graph.node if n.op_type == "Add"]
        assert len(add_nodes) == 1
        assert add_nodes[0].output[0] in matmul.input
        onnx.checker.check_model(result)

    def test_numerics_unchanged_rhs_constant(self) -> None:
        """+0 untie leaves outputs identical (constant on RHS, dynamic batch)."""
        model = _build_model(const_on_rhs=True)
        result = _rewrite(model)
        feed = {"dyn": np.random.RandomState(7).randn(2, 3, 4).astype(np.float32)}
        np.testing.assert_array_equal(_run(model, feed), _run(result, feed))

    def test_numerics_unchanged_lhs_constant(self) -> None:
        """Constant on the LHS is untied and stays numerically identical."""
        model = _build_model(const_on_rhs=False)
        result = _rewrite(model)
        assert any(n.op_type == "Add" for n in result.graph.node)
        feed = {"dyn": np.random.RandomState(7).randn(2, 4, 5).astype(np.float32)}
        np.testing.assert_array_equal(_run(model, feed), _run(result, feed))

    def test_symbolic_dynamic_dims_are_matched(self) -> None:
        """The dynamic operand may carry symbolic dims (the real transformer case)."""
        model = _build_model(const_on_rhs=True, dynamic_batch=True)
        result = _rewrite(model)
        # Match succeeded despite the symbolic batch dim on the activation operand.
        assert any(n.op_type == "Add" for n in result.graph.node)

    def test_rank2_constant_is_left_untouched(self) -> None:
        """A rank-2 constant gemm compiles on OV GPU, so it must not be rewritten."""
        model = _build_model(const_on_rhs=True, const_rank=2)
        result = _rewrite(model)
        assert not any(n.op_type == "Add" for n in result.graph.node)

    def test_all_constant_matmul_is_left_untouched(self) -> None:
        """A MatMul whose operands are both constant folds away; do not rewrite it."""
        model = _build_model(const_on_rhs=True, both_constant=True)
        result = _rewrite(model)
        assert not any(n.op_type == "Add" for n in result.graph.node)
