# --------------------------------------------------------------------------
# ⚠️ WARNING - AUTO-GENERATED CODE - DO NOT EDIT ⚠️
# ⚙️ Generated by 'python -m opgen'
# --------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.
# --------------------------------------------------------------------------
# pylint: disable=W0221,W0222,R0901,W0237
# mypy: disable-error-code=override
# --------------------------------------------------------------------------

from __future__ import annotations

from typing import TYPE_CHECKING

from onnx.defs import onnx_opset_version
from onnxscript.onnx_opset import *
from onnxscript.onnx_opset import __all__ as onnxscript_opset_all
from onnxscript.onnx_opset import all_opsets as onnxscript_all_opsets

from ._impl.opset_ai_onnx_preview_training1 import Opset_ai_onnx_preview_training1
from ._impl.opset_com_microsoft1 import Opset_com_microsoft1

if TYPE_CHECKING:
    from onnx import ModelProto


__all__ = [
    *onnxscript_opset_all,
    "opset_com_microsoft1",
    "opset_ai_onnx_preview_training1",
]


if onnx_opset_version() < 14:
    raise ImportError(
        f"ONNX Script requires ONNX opset >= 14 but {onnx_opset_version()} is detected."
    )


opset_com_microsoft1 = Opset_com_microsoft1()
opset_ai_onnx_preview_training1 = Opset_ai_onnx_preview_training1()

# Custom domains to register from ONNX Runtime
_CUSTOM_DOMAINS_TO_REGISTER = {"com.microsoft"}


# Initialize custom domain schemas before importing opset modules
def _init_custom_schemas(domains: set[str] | None = None):
    """Load and register custom domain operator schemas from ONNX Runtime.

    This function uses onnxruntime.capi.onnxruntime_pybind11_state.get_all_operator_schema()
    to retrieve schemas for custom domains and registers them with ONNX.
    This allows custom domain operators to work seamlessly with get_schema() calls.

    Args:
        domains: Set of domain names to register. If None, uses _CUSTOM_DOMAINS.
    """
    if domains is None:
        domains = _CUSTOM_DOMAINS_TO_REGISTER

    if not domains:
        return

    try:
        from onnxruntime.capi.onnxruntime_pybind11_state import get_all_operator_schema
    except ImportError:
        # ONNX Runtime not installed, skip custom schema registration
        return

    import onnx.defs as onnx_defs_module

    # Get all schemas from ONNX Runtime and filter for specified domains
    for ort_schema in get_all_operator_schema():
        # Skip domains not in the specified set
        if ort_schema.domain not in domains:
            continue

        try:
            # Convert inputs to FormalParameter list
            inputs = [
                OpSchema.FormalParameter(
                    inp.name,
                    inp.typeStr,
                    inp.description,
                    param_option=OpSchema.FormalParameterOption(inp.option.value),
                )
                for inp in ort_schema.inputs
            ]

            # Convert outputs to FormalParameter list
            outputs = [
                OpSchema.FormalParameter(
                    out.name,
                    out.typeStr,
                    out.description,
                    param_option=OpSchema.FormalParameterOption(out.option.value),
                )
                for out in ort_schema.outputs
            ]

            # Convert type constraints to tuple list format
            type_constraints = [
                (tc.type_param_str, tc.allowed_type_strs, tc.description)
                for tc in ort_schema.type_constraints
            ]

            # Convert attributes to Attribute list
            attributes = [
                OpSchema.Attribute(
                    attr.name,
                    OpSchema.AttrType(attr.type.value),
                    attr.description,
                    required=attr.required,
                )
                for attr in ort_schema.attributes.values()
            ]

            # Create and register the schema
            schema = OpSchema(
                ort_schema.name,
                ort_schema.domain,
                ort_schema.since_version,
                ort_schema.doc or "",
                inputs=inputs,
                outputs=outputs,
                type_constraints=type_constraints,
                attributes=attributes,
            )

            onnx_defs_module.register_schema(schema)

        except Exception:
            # Silently skip schemas that fail to register
            continue


# Load com.microsoft domain schemas
_init_custom_schemas(_CUSTOM_DOMAINS_TO_REGISTER)


# Combine all opsets: standard ONNX opsets + custom opsets
all_opsets = {
    **onnxscript_all_opsets,  # Include all standard ONNX opsets
    (
        "com.microsoft",
        1,
    ): opset_com_microsoft1,
    (
        "ai.onnx.preview.training",
        1,
    ): opset_ai_onnx_preview_training1,
}
