# -------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License.
# --------------------------------------------------------------------------
"""JSON-based rewrite group discovery and validation for RewritePipe.

Rewrite capabilities are derived from SkeletonPatternRules in
modelkit/pattern/rules/*.json. Entries sharing the same (pattern_id,
target_class) are grouped into one RewriteGroup — one CLI flag that applies
all source variants in one shot.
"""

from __future__ import annotations

import importlib
import json
import logging
import re
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

from winml.modelkit.pattern.base import Pattern


logger = logging.getLogger(__name__)


@dataclass
class RewriteRule:
    """A single rewrite rule: match source pattern, replace with target.

    Attributes:
        source: Pattern instance that defines what to match (get_skeleton).
        target: Pattern instance that defines the replacement topology.
    """

    source: Pattern
    target: Pattern


@dataclass
class RewriteGroup:
    """All source patterns that rewrite to the same target under one pattern_id.

    Attributes:
        pattern_id:              Original pattern_id (e.g. "SUBGRAPH/GeluPattern").
        flag_source:             pattern_id slug for multi-source; source class for single.
        target_class:            Target pattern class name.
        sources:                 Ordered list of source pattern class names.
        rule_file:               Path to the JSON file that defined this group.
        flag_name_override:      Per-source JSON ``flag_name`` (single-source groups only).
        target_flag_name_override: JSON ``flag_name`` from the alternative entry;
                                 overrides the auto-generated target slug.
    """

    pattern_id: str
    flag_source: str
    target_class: str
    sources: list[str] = field(default_factory=list)
    rule_file: str = ""
    flag_name_override: str = ""
    target_flag_name_override: str = ""

    @property
    def flag_name(self) -> str:
        """CLI capability name for this group (all lowercase).

        Single-source groups: the JSON ``flag_name`` field (``flag_name_override``)
        takes precedence; otherwise auto-generated from the source class name.

        Multi-source groups: always derived from the ``pattern_id`` tail
        (``SUBGRAPH/GeluPattern`` → ``gelu``).  The per-entry ``flag_name``
        is only used for individual per-source flags, not the group flag.

        Target slug: uses ``target_flag_name_override`` when set; otherwise
        auto-generated by stripping the ``Pattern`` suffix from ``target_class``.

        Examples:
            SUBGRAPH/GeluPattern  (4 sources) → "gelu-singlegelu"
            MatMulAddPattern      (1 source, override "matmuladd", target "reshapegemm")
                                            → "matmuladd-reshapegemm"
        """
        target_slug = self.target_flag_name_override or re.sub(
            r"pattern$", "", self.target_class.lower()
        )
        if len(self.sources) == 1:
            if self.flag_name_override:
                return f"{self.flag_name_override}-{target_slug}"
            source_slug = re.sub(r"pattern$", "", self.sources[0].lower())
            return f"{source_slug}-{target_slug}"
        # Multi-source: derive source slug from pattern_id tail
        tail = self.pattern_id.split("/")[-1]  # e.g. "GeluPattern"
        source_slug = re.sub(r"(?i)pattern$", "", tail).lower()  # "gelu"
        return f"{source_slug}-{target_slug}"


# Registry populated by _load_rewrite_groups()
_CLASS_NAME_TO_PATTERN: dict[str, type] = {}
# Per-source flag overrides: (source_class, target_class) → flag_name override
# Populated as a side effect of _load_rewrite_groups().
_SOURCE_FLAG_OVERRIDES: dict[tuple[str, str], str] = {}
# Target flag overrides: target_class → flag_name override from alternatives[].flag_name
# Populated as a side effect of _load_rewrite_groups().
_TARGET_FLAG_OVERRIDES: dict[str, str] = {}


def _find_pattern_class(name: str) -> type:
    """Look up a pattern class by name from the registry.

    Raises:
        ValueError: If the pattern name is not registered.
    """
    if name not in _CLASS_NAME_TO_PATTERN:
        raise ValueError(
            f"Unknown pattern: '{name}'. Use --list-rewrites to see available patterns."
        )
    return _CLASS_NAME_TO_PATTERN[name]


def _load_rewrite_groups() -> list[RewriteGroup]:
    """Scan all *.json rule files in modelkit/pattern/rules/ and build RewriteGroup list.

    Algorithm:
    1. For each file, iterate SkeletonPatternRules entries.
    2. Collect (pattern_id, target_class, source_class) triples.
    3. Group by (pattern_id, target_class) → same group = same CLI flag.
    4. Finalize flag_source: pattern_id slug for multi-source, class name for single.

    Side effect: populates _CLASS_NAME_TO_PATTERN.
    """
    rules_dir = Path(__file__).parent.parent.parent / "pattern" / "rules"
    groups: dict[tuple[str, str], RewriteGroup] = {}

    for json_path in sorted(rules_dir.glob("*.json")):
        try:
            data = json.loads(json_path.read_text(encoding="utf-8"))
        except json.JSONDecodeError as exc:
            logger.warning(
                "Invalid JSON in %s (line %d, col %d: %s), skipping file",
                json_path,
                exc.lineno,
                exc.colno,
                exc.msg,
            )
            continue
        for entry in data.get("SkeletonPatternRules", []):
            try:
                pattern_id = entry["pattern_id"]
                source_class = entry["pattern_class"]
                source_module = entry["module"]
            except KeyError as exc:
                logger.warning(
                    "Missing key %s in entry of %s, skipping entry",
                    exc,
                    json_path,
                )
                continue

            try:
                mod = importlib.import_module(source_module)
                cls = getattr(mod, source_class, None)
                if cls is None:
                    logger.warning(
                        "Class %s not found in module %s, skipping entry",
                        source_class,
                        entry.get("module"),
                    )
                    continue
                _CLASS_NAME_TO_PATTERN[source_class] = cls
            except ImportError:
                logger.warning(
                    "Failed to import %s for pattern %s",
                    entry.get("module"),
                    entry.get("pattern_class"),
                )
                continue

            for alt in entry.get("alternatives", []):
                try:
                    target_class = alt["pattern_class"]
                    target_module = alt["module"]
                except KeyError as exc:
                    logger.warning(
                        "Missing key %s in alternative of %s, skipping alternative",
                        exc,
                        json_path,
                    )
                    continue

                try:
                    tmod = importlib.import_module(target_module)
                    tcls = getattr(tmod, target_class, None)
                    if tcls is None:
                        logger.warning(
                            "Class %s not found in module %s, skipping alternative",
                            target_class,
                            target_module,
                        )
                        continue
                    _CLASS_NAME_TO_PATTERN[target_class] = tcls
                except ImportError:
                    logger.warning(
                        "Failed to import %s for pattern %s",
                        alt.get("module"),
                        alt.get("pattern_class"),
                    )
                    continue

                key = (pattern_id, target_class)
                if key not in groups:
                    groups[key] = RewriteGroup(
                        pattern_id=pattern_id,
                        flag_source=pattern_id,
                        target_class=target_class,
                        sources=[],
                        rule_file=str(json_path),
                        # flag_name_override is only meaningful for single-source groups;
                        # for multi-source the group flag derives from pattern_id.
                        flag_name_override=entry.get("flag_name", ""),
                        target_flag_name_override=alt.get("flag_name", ""),
                    )
                if source_class not in groups[key].sources:
                    groups[key].sources.append(source_class)
                # Store per-source flag override regardless of group size.
                if entry.get("flag_name"):
                    _SOURCE_FLAG_OVERRIDES[(source_class, target_class)] = entry["flag_name"]
                # Store target flag override.
                if alt.get("flag_name"):
                    _TARGET_FLAG_OVERRIDES[target_class] = alt["flag_name"]

    result = []
    for group in groups.values():
        if len(group.sources) == 1:
            group.flag_source = group.sources[0]
        else:
            # Multi-source: clear flag_name_override so flag_name uses pattern_id.
            group.flag_name_override = ""
        result.append(group)

    return result


REWRITE_GROUPS: list[RewriteGroup] = _load_rewrite_groups()


def source_flag_name(source_class: str, target_class: str) -> str:
    """Return the individual per-source flag name.

    Source slug: uses JSON ``flag_name`` from the source entry when present;
    otherwise auto-generated by stripping ``Pattern`` suffix.
    Target slug: uses JSON ``flag_name`` from the alternative entry when present;
    otherwise auto-generated by stripping ``Pattern`` suffix.
    """
    tgt_slug = _TARGET_FLAG_OVERRIDES.get(target_class) or re.sub(
        r"pattern$", "", target_class.lower()
    )
    override = _SOURCE_FLAG_OVERRIDES.get((source_class, target_class), "")
    if override:
        return f"{override}-{tgt_slug}"
    src_slug = re.sub(r"pattern$", "", source_class.lower())
    return f"{src_slug}-{tgt_slug}"


def _build_rewrite_capabilities() -> dict[str, Any]:
    """Generate one BoolCapability per RewriteGroup plus per-source caps for multi-source groups.

    Multi-source groups register two kinds of flags:
    - Group flag  (e.g. ``gelu-singlegelu``)      → applies ALL source variants at once.
    - Per-source flags (e.g. ``gelu1-singlegelu``) → applies only that one variant.
    Single-source groups register only the group flag (the two would be identical).
    """
    from winml.modelkit.optim.registry import BoolCapability, CapabilityCategory

    caps: dict[str, BoolCapability] = {}
    for group in REWRITE_GROUPS:
        name = group.flag_name
        sources_str = ", ".join(group.sources)
        caps[name] = BoolCapability(
            name=name,
            ort_name=None,
            description=f"Rewrite [{sources_str}] → {group.target_class}",
            category=CapabilityCategory.REWRITE,
            default=False,
        )
        # For multi-source groups, also register individual per-source flags.
        if len(group.sources) > 1:
            for src in group.sources:
                src_flag = source_flag_name(src, group.target_class)
                if src_flag not in caps:
                    caps[src_flag] = BoolCapability(
                        name=src_flag,
                        ort_name=None,
                        description=f"Rewrite {src} → {group.target_class}",
                        category=CapabilityCategory.REWRITE,
                        default=False,
                    )
    return caps


REWRITE_CAPABILITIES: dict[str, Any] = _build_rewrite_capabilities()

# Precomputed O(1) lookup: group flag_name → RewriteGroup
_FLAG_NAME_TO_GROUP: dict[str, RewriteGroup] = {g.flag_name: g for g in REWRITE_GROUPS}

# Precomputed O(1) lookup: per-source flag → (source_class, target_class)
# Only populated for multi-source groups (avoids duplication with single-source group flags).
_FLAG_NAME_TO_SOURCE: dict[str, tuple[str, str]] = {
    source_flag_name(src, g.target_class): (src, g.target_class)
    for g in REWRITE_GROUPS
    if len(g.sources) > 1
    for src in g.sources
}


def get_rewrite_rules_for_capability(cap_name: str) -> list[RewriteRule]:
    """Return all RewriteRules for an enabled capability.

    Group flag (e.g. ``gelu-singlegelu``) returns one RewriteRule per source
    variant.  Per-source flag (e.g. ``gelu1-singlegelu``) returns exactly one
    RewriteRule for that specific variant.

    Args:
        cap_name: CLI capability name (kebab-case, all lowercase).

    Returns:
        List of RewriteRule instances.

    Raises:
        ValueError: If the capability name is not registered.
    """
    group = _FLAG_NAME_TO_GROUP.get(cap_name)
    if group is not None:
        target_cls = _find_pattern_class(group.target_class)
        return [
            RewriteRule(source=_find_pattern_class(src)(), target=target_cls())
            for src in group.sources
        ]
    src_target = _FLAG_NAME_TO_SOURCE.get(cap_name)
    if src_target is not None:
        src_class, tgt_class = src_target
        return [
            RewriteRule(
                source=_find_pattern_class(src_class)(),
                target=_find_pattern_class(tgt_class)(),
            )
        ]
    raise ValueError(
        f"Unknown rewrite capability: '{cap_name}'. "
        "Use --list-rewrites to see available capabilities."
    )


def list_rewrite_families() -> dict[str, list[str]]:
    """Return all rewrite groups as {pattern_id: [sources..., target]}.

    Key is the original pattern_id (e.g. "SUBGRAPH/GeluPattern").
    Value is sources list followed by the target class name.

    Used for --list-rewrites display and test helpers.
    """
    result: dict[str, list[str]] = {}
    for group in REWRITE_GROUPS:
        members = [*group.sources, group.target_class]
        if group.pattern_id in result:
            # Append new members that aren't already present to avoid
            # overwriting when two groups share the same pattern_id
            # but have different targets.
            for m in members:
                if m not in result[group.pattern_id]:
                    result[group.pattern_id].append(m)
        else:
            result[group.pattern_id] = members
    return result
