# -------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License.
# --------------------------------------------------------------------------

"""Tests for Florence-2 split image-to-text export."""

from __future__ import annotations

import json
from pathlib import Path
from types import SimpleNamespace
from typing import ClassVar

import torch
from optimum.exporters.tasks import TasksManager
from transformers.modeling_outputs import BaseModelOutput

from winml.modelkit.config import WinMLBuildConfig
from winml.modelkit.export import generate_dummy_inputs, resolve_io_specs
from winml.modelkit.export.config import _resolve_export_config_from_specs
from winml.modelkit.models import HF_MODEL_CLASS_MAPPING


_RECIPE_DIR = Path("examples/recipes/microsoft_Florence-2-base")


def _florence2_config():
    from transformers import Florence2Config

    return Florence2Config()


def _florence2_base_config():
    from transformers import Florence2Config

    return Florence2Config(
        text_config={
            "d_model": 768,
            "decoder_attention_heads": 12,
            "decoder_layers": 6,
            "vocab_size": 51289,
        }
    )


def _load_recipe(name: str) -> dict:
    return json.loads((_RECIPE_DIR / name).read_text())


class TestFlorence2Registration:
    def test_class_mapping_contains_encoder(self) -> None:
        assert ("florence2", "feature-extraction") in HF_MODEL_CLASS_MAPPING

    def test_class_mapping_contains_decoder(self) -> None:
        assert ("florence2", "text2text-generation") in HF_MODEL_CLASS_MAPPING

    def test_encoder_config_registered(self) -> None:
        constructor = TasksManager.get_exporter_config_constructor(
            exporter="onnx",
            model_type="florence2",
            task="feature-extraction",
            library_name="transformers",
        )

        assert constructor.func.__name__ == "Florence2EncoderIOConfig"

    def test_decoder_config_registered(self) -> None:
        constructor = TasksManager.get_exporter_config_constructor(
            exporter="onnx",
            model_type="florence2",
            task="text2text-generation",
            library_name="transformers",
        )

        assert constructor.func.__name__ == "Florence2DecoderIOConfig"

    def test_composite_registered(self) -> None:
        from winml.modelkit.models.winml.composite_model import COMPOSITE_MODEL_REGISTRY

        assert ("florence2", "image-to-text") in COMPOSITE_MODEL_REGISTRY


class TestFlorence2IO:
    def test_encoder_accepts_image_and_prompt_inputs(self) -> None:
        specs = resolve_io_specs("florence2", "feature-extraction", _florence2_config())

        assert specs["input_names"] == ["input_ids", "pixel_values", "attention_mask"]
        assert specs["output_names"] == ["last_hidden_state"]
        assert specs["input_shapes"][0] == (1, 8)
        assert specs["dummy_value_runs"]["input_ids"] == ((8, 0),)

    def test_decoder_has_static_cache_io(self) -> None:
        specs = resolve_io_specs("florence2", "text2text-generation", _florence2_config())
        assert {"decoder_input_ids", "encoder_hidden_states", "cache_position"} <= set(
            specs["input_names"]
        )
        assert specs["output_names"][0] == "logits"

    def test_decoder_metadata_marks_encoder_source_axes_dynamic(self) -> None:
        specs = resolve_io_specs("florence2", "text2text-generation", _florence2_config())

        assert specs["dynamic_axes"]["encoder_hidden_states"] == {
            0: "batch_size",
            1: "sequence_length",
        }
        assert specs["dynamic_axes"]["decoder_input_ids"] == {0: "batch_size"}
        assert specs["dynamic_axes"]["decoder_attention_mask"] == {0: "batch_size"}
        assert specs["dynamic_axes"]["past_0_key"] == {0: "batch_size"}

    def test_encoder_export_config_recreates_generator_inputs(self) -> None:
        """Semantic dummy values generated by an ONNX config survive export config construction."""
        config = _florence2_config()
        generated_inputs = generate_dummy_inputs("florence2", "feature-extraction", config)

        export_config = _resolve_export_config_from_specs(
            "florence2",
            "feature-extraction",
            config,
        )

        recreated_inputs = export_config.generate_dummy_inputs()
        for name, generated in generated_inputs.items():
            assert torch.equal(recreated_inputs[name], generated)

    def test_encoder_prepends_image_features_to_text_embeddings(self) -> None:
        """The upstream model combines its image embeddings with prompt embeddings."""
        config = SimpleNamespace()

        def embed(input_ids: torch.Tensor) -> torch.Tensor:
            return torch.zeros((*input_ids.shape, 2))

        def merge(
            image_features: torch.Tensor, inputs_embeds: torch.Tensor
        ) -> tuple[torch.Tensor, torch.Tensor]:
            combined = torch.cat((image_features, inputs_embeds), dim=1)
            return combined, torch.ones(combined.shape[:2], dtype=torch.long)

        fake_model = SimpleNamespace(
            get_input_embeddings=lambda: embed,
            _encode_image=lambda pixel_values: torch.zeros((1, 2, 2)),
            _merge_input_ids_with_image_features=merge,
            get_encoder=lambda: lambda **kwargs: SimpleNamespace(
                last_hidden_state=kwargs["inputs_embeds"]
            ),
        )
        wrapper_class = HF_MODEL_CLASS_MAPPING[("florence2", "feature-extraction")]
        wrapper = wrapper_class(fake_model, config)

        output = wrapper(
            input_ids=torch.tensor([[5, 5, 0]]),
            pixel_values=torch.zeros((1, 3, 2, 2)),
            attention_mask=torch.ones((1, 3), dtype=torch.long),
        )

        assert output.shape == (1, 5, 2)

    def test_encoder_preserves_padded_text_masks_after_image_prefix(self) -> None:
        """Image-token masks must be prefixed without unmasking padded prompt tokens."""
        config = SimpleNamespace()
        received: dict[str, torch.Tensor] = {}

        def embed(input_ids: torch.Tensor) -> torch.Tensor:
            return torch.zeros((*input_ids.shape, 2))

        def merge(
            image_features: torch.Tensor, inputs_embeds: torch.Tensor
        ) -> tuple[torch.Tensor, torch.Tensor]:
            combined = torch.cat((image_features, inputs_embeds), dim=1)
            return combined, torch.ones(combined.shape[:2], dtype=torch.long)

        def encoder(**kwargs: torch.Tensor) -> SimpleNamespace:
            received.update(kwargs)
            return SimpleNamespace(last_hidden_state=kwargs["inputs_embeds"])

        fake_model = SimpleNamespace(
            get_input_embeddings=lambda: embed,
            _encode_image=lambda pixel_values: torch.zeros((pixel_values.size(0), 2, 2)),
            _merge_input_ids_with_image_features=merge,
            get_encoder=lambda: encoder,
        )
        wrapper_class = HF_MODEL_CLASS_MAPPING[("florence2", "feature-extraction")]
        wrapper = wrapper_class(fake_model, config)
        attention_mask = torch.tensor([[1, 1, 0], [1, 0, 0]], dtype=torch.long)

        wrapper(
            input_ids=torch.tensor([[5, 6, 0], [7, 0, 0]]),
            pixel_values=torch.zeros((2, 3, 2, 2)),
            attention_mask=attention_mask,
        )

        assert torch.equal(
            received["attention_mask"],
            torch.tensor([[1, 1, 1, 1, 0], [1, 1, 1, 0, 0]], dtype=torch.long),
        )


class TestFlorence2DecoderWrapper:
    @staticmethod
    def _cache(layer_count: int = 2) -> SimpleNamespace:
        return SimpleNamespace(
            layers=[
                SimpleNamespace(
                    keys=torch.full((1, 2, 4, 3), float(index + 1)),
                    values=torch.full((1, 2, 4, 3), float(index + 11)),
                )
                for index in range(layer_count)
            ],
            captured={},
        )

    @staticmethod
    def _inputs(cache_position: int) -> dict[str, torch.Tensor]:
        return {
            "decoder_input_ids": torch.tensor([[7]]),
            "decoder_attention_mask": torch.ones((1, 5), dtype=torch.long),
            "encoder_hidden_states": torch.zeros((1, 3, 4)),
            "cache_position": torch.tensor(cache_position),
        }

    def test_invokes_legacy_decoder_with_empty_cache_at_position_zero(self) -> None:
        cache = self._cache()
        returned = tuple(
            (
                torch.full((1, 2, 1, 3), float(index + 21)),
                torch.full((1, 2, 1, 3), float(index + 31)),
            )
            for index in range(len(cache.layers))
        )
        received: dict[str, object] = {}

        def decoder(**kwargs: object) -> SimpleNamespace:
            received.update(kwargs)
            return SimpleNamespace(
                last_hidden_state=torch.ones((1, 1, 4)),
                past_key_values=returned,
            )

        wrapper = HF_MODEL_CLASS_MAPPING[("florence2", "text2text-generation")]()
        wrapper.model = SimpleNamespace(
            get_decoder=lambda: decoder,
            language_model=SimpleNamespace(lm_head=lambda hidden_states: hidden_states),
        )

        logits = wrapper._invoke_hf(cache, self._inputs(cache_position=0))

        legacy_cache = received["past_key_values"]
        assert isinstance(legacy_cache, tuple)
        assert [len(layer) for layer in legacy_cache] == [2] * len(cache.layers)
        assert [layer[0].shape[2] for layer in legacy_cache] == [0] * len(cache.layers)
        assert received["attention_mask"].shape == (1, 1)
        for index, (key, value) in enumerate(returned):
            assert torch.equal(cache.captured[index][0], key)
            assert torch.equal(cache.captured[index][1], value)
        assert torch.equal(logits, torch.ones((1, 1, 4)))

    def test_uses_active_prefix_for_later_cache_position(self) -> None:
        cache = self._cache()
        returned = tuple(
            (
                torch.full((1, 2, 3, 3), float(index + 41)),
                torch.full((1, 2, 3, 3), float(index + 51)),
            )
            for index in range(len(cache.layers))
        )
        received: dict[str, object] = {}

        def decoder(**kwargs: object) -> SimpleNamespace:
            received.update(kwargs)
            return SimpleNamespace(
                last_hidden_state=torch.ones((1, 1, 4)),
                past_key_values=returned,
            )

        wrapper = HF_MODEL_CLASS_MAPPING[("florence2", "text2text-generation")]()
        wrapper.model = SimpleNamespace(
            get_decoder=lambda: decoder,
            language_model=SimpleNamespace(lm_head=lambda hidden_states: hidden_states),
        )

        wrapper._invoke_hf(cache, self._inputs(cache_position=2))

        legacy_cache = received["past_key_values"]
        assert isinstance(legacy_cache, tuple)
        assert [layer[0].shape[2] for layer in legacy_cache] == [2] * len(cache.layers)
        assert torch.equal(legacy_cache[1][1], cache.layers[1].values[:, :, :2, :])
        assert received["attention_mask"].shape == (1, 3)
        for index, (key, value) in enumerate(returned):
            assert torch.equal(cache.captured[index][0], key[:, :, 2:, :])
            assert torch.equal(cache.captured[index][1], value[:, :, 2:, :])


class TestFlorence2Recipes:
    def test_decoder_recipe_declares_only_dynamic_encoder_axes(self) -> None:
        export = _load_recipe("image-to-text_fp16_config_decoder.json")["export"]

        assert export["dynamic_axes"] == {
            "encoder_hidden_states": {
                "0": "batch_size",
                "1": "source_sequence_length",
            }
        }

    def test_decoder_recipe_assembles_dynamic_source_shape(self) -> None:
        config = WinMLBuildConfig.from_dict(
            _load_recipe("image-to-text_fp16_config_decoder.json")
        )

        assert config.export is not None
        assert config.export.dynamic_axes == {
            "encoder_hidden_states": {
                0: "batch_size",
                1: "source_sequence_length",
            }
        }
        assert next(
            tensor
            for tensor in config.export.input_tensors or []
            if tensor.name == "encoder_hidden_states"
        ).shape == (1, 16, 768)

    def test_component_recipes_share_remote_code_consent(self) -> None:
        encoder_loader = _load_recipe("image-to-text_fp16_config_encoder.json")["loader"]
        decoder_loader = _load_recipe("image-to-text_fp16_config_decoder.json")["loader"]

        assert encoder_loader["trust_remote_code"] is True
        assert decoder_loader["trust_remote_code"] is True

    def test_native_loader_and_processor_forward_explicit_consent(self, monkeypatch) -> None:
        from winml.modelkit.models.hf.florence2 import (
            _load_native_combined_processor,
            _NativeFlorence2ForConditionalGeneration,
        )

        model_kwargs: dict[str, object] = {}
        processor_kwargs: dict[str, object] = {}

        def load_model(*args: object, **kwargs: object) -> tuple[object, dict[str, list[str]]]:
            model_kwargs.update(kwargs)
            return object(), {
                "missing_keys": [],
                "unexpected_keys": [],
                "mismatched_keys": [],
            }

        def load_processor(*args: object, **kwargs: object) -> object:
            processor_kwargs.update(kwargs)
            return object()

        monkeypatch.setattr("transformers.AutoModelForCausalLM.from_pretrained", load_model)
        monkeypatch.setattr("transformers.AutoProcessor.from_pretrained", load_processor)

        _NativeFlorence2ForConditionalGeneration.from_pretrained(
            "local-model",
            trust_remote_code=False,
        )
        _load_native_combined_processor("local-model", trust_remote_code=False)

        assert model_kwargs["trust_remote_code"] is False
        assert processor_kwargs["trust_remote_code"] is False

    def test_decoder_recipe_matches_base_text_config(self) -> None:
        config = _florence2_base_config()
        export = _load_recipe("image-to-text_fp16_config_decoder.json")["export"]
        tensors = export["input_tensors"]
        shapes = {tensor["name"]: tensor["shape"] for tensor in tensors}
        value_ranges = {
            tensor["name"]: tensor["value_range"] for tensor in tensors if "value_range" in tensor
        }
        past_key_names = [
            name for name in shapes if name.startswith("past_") and name.endswith("_key")
        ]
        output_names = [tensor["name"] for tensor in export["output_tensors"]]

        assert shapes["encoder_hidden_states"][2] == config.text_config.d_model
        assert shapes["past_0_key"][1] == config.text_config.decoder_attention_heads
        assert shapes["past_0_key"][3] == (
            config.text_config.d_model // config.text_config.decoder_attention_heads
        )
        assert value_ranges["decoder_input_ids"] == [0, config.text_config.vocab_size]
        assert past_key_names == [
            f"past_{index}_key" for index in range(config.text_config.decoder_layers)
        ]
        assert output_names == [
            "logits",
            *(
                name
                for index in range(config.text_config.decoder_layers)
                for name in (f"present_{index}_key", f"present_{index}_value")
            ),
        ]


class TestFlorence2Generation:
    def test_prompt_ids_stay_on_encoder_and_decoder_steps_are_single_token(self) -> None:
        """Prompt IDs must remain encoder inputs when the primary input is pixels."""
        from winml.modelkit.models.hf.florence2 import WinMLFlorence2ImageToText

        class Encoder:
            io_config: ClassVar[dict[str, list[object]]] = {
                "input_names": ["input_ids", "pixel_values", "attention_mask"],
                "input_shapes": [[1, 8], [1, 3, 2, 2], [1, 8]],
            }

            def __call__(self, **kwargs: torch.Tensor) -> BaseModelOutput:
                return BaseModelOutput(last_hidden_state=torch.zeros((1, 2, 4)))

        class Decoder:
            io_config: ClassVar[dict[str, list[object]]] = {
                "input_names": [
                    "decoder_input_ids",
                    "encoder_hidden_states",
                    "decoder_attention_mask",
                    "cache_position",
                    "past_0_key",
                    "past_0_value",
                ],
                "input_shapes": [
                    [1, 1],
                    [1, 2, 4],
                    [1, 4],
                    [1],
                    [1, 1, 4, 4],
                    [1, 1, 4, 4],
                ],
                "input_types": [int, float, int, int, "float32", "float32"],
            }

            def __init__(self) -> None:
                self.decoder_input_ids: list[torch.Tensor] = []

            def __call__(self, **kwargs: torch.Tensor) -> dict[str, torch.Tensor]:
                self.decoder_input_ids.append(kwargs["decoder_input_ids"].clone())
                logits = torch.zeros((1, 1, 8))
                logits[:, :, 3] = 1
                return {
                    "logits": logits,
                    "present_0_key": torch.zeros((1, 1, 1, 4)),
                    "present_0_value": torch.zeros((1, 1, 1, 4)),
                }

        config = _florence2_base_config()
        config.text_config.num_hidden_layers = 1
        config.text_config.decoder_layers = 1
        decoder = Decoder()
        model = WinMLFlorence2ImageToText(
            {"encoder": Encoder(), "decoder": decoder},
            config,
        )

        model.generate(
            pixel_values=torch.zeros((1, 3, 2, 2)),
            input_ids=torch.arange(8).reshape(1, 8),
            attention_mask=torch.ones((1, 8), dtype=torch.long),
            max_new_tokens=2,
            eos_token_id=None,
        )

        assert [tuple(ids.shape) for ids in decoder.decoder_input_ids] == [(1, 1), (1, 1)]
